-- MySQL Script generated by MySQL Workbench
-- 01/19/17 11:21:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema secutel-erp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema secutel-erp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secutel-erp` DEFAULT CHARACTER SET latin1 ;
USE `secutel-erp` ;

-- -----------------------------------------------------
-- Table `secutel-erp`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idcategoria`)  COMMENT '',
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `cedula` VARCHAR(10) NOT NULL COMMENT '',
  `telefono` VARCHAR(10) NOT NULL COMMENT '',
  `correo` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idcliente`)  COMMENT '',
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC)  COMMENT '',
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`proveedor` (
  `idproveedor` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `ruc` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idproveedor`)  COMMENT '',
  UNIQUE INDEX `idproveedor_UNIQUE` (`idproveedor` ASC)  COMMENT '',
  UNIQUE INDEX `ruc_UNIQUE` (`ruc` ASC)  COMMENT '',
  UNIQUE INDEX `direccion_UNIQUE` (`direccion` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`contacto_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`contacto_proveedor` (
  `idcontacto_proveedor` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idproveedor` INT(11) NOT NULL COMMENT '',
  `nombres` VARCHAR(45) NOT NULL COMMENT '',
  `apellidos` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT 'activo o inactivo ',
  PRIMARY KEY (`idcontacto_proveedor`)  COMMENT '',
  UNIQUE INDEX `idcontacto_proveedor_UNIQUE` (`idcontacto_proveedor` ASC)  COMMENT '',
  INDEX `fk_contacto_proveedor_proveedor1_idx` (`idproveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_contacto_proveedor_proveedor1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `secutel-erp`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`empleado` (
  `idempleado` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `cedula` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `fecha_nacimiento` DATE NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT 'puede ser: vendedor o Administrador',
  `estado` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idempleado`)  COMMENT '',
  UNIQUE INDEX `idempleado_UNIQUE` (`idempleado` ASC)  COMMENT '',
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`cotizacion` (
  `idCotizacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idcliente` INT(11) NOT NULL COMMENT '',
  `idvendedor` INT(11) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `vigencia` DATE NOT NULL COMMENT '',
  `estado` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad_total_productos` INT(11) NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una cotizacion, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  `sub_total` DOUBLE NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una cotizacion, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  `iva` DOUBLE NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una cotizacion, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  `total_pagar` DOUBLE NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una cotizacion, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  PRIMARY KEY (`idCotizacion`)  COMMENT '',
  UNIQUE INDEX `idCotizacion_UNIQUE` (`idCotizacion` ASC)  COMMENT '',
  INDEX `fk_cotizacion_cliente1_idx` (`idcliente` ASC)  COMMENT '',
  INDEX `fk_cotizacion_empleado1_idx` (`idvendedor` ASC)  COMMENT '',
  CONSTRAINT `fk_cotizacion_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `secutel-erp`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotizacion_empleado1`
    FOREIGN KEY (`idvendedor`)
    REFERENCES `secutel-erp`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`credenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`credenciales` (
  `idcredenciales` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idempleado` INT(11) NOT NULL COMMENT '',
  `usuario` VARCHAR(45) NOT NULL COMMENT '',
  `clave` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idcredenciales`)  COMMENT '',
  UNIQUE INDEX `idcredenciales_UNIQUE` (`idcredenciales` ASC)  COMMENT '',
  INDEX `fk_credenciales_empleado1_idx` (`idempleado` ASC)  COMMENT '',
  CONSTRAINT `fk_credenciales_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `secutel-erp`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idcategoria` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `marca` VARCHAR(45) NULL DEFAULT NULL COMMENT 'este dato puede ser null ya que si ingresamos un servicio, el mismo no posee una marca, modelo o serie.',
  `modelo` VARCHAR(45) NULL DEFAULT NULL COMMENT 'este dato puede ser null ya que si ingresamos un servicio, el mismo no posee una marca, modelo o serie.',
  `valor` DOUBLE NOT NULL COMMENT '',
  `minimo` INT(11) NULL DEFAULT NULL COMMENT '',
  `maximo` INT(11) NULL DEFAULT NULL COMMENT '',
  `existencia` INT(11) NULL DEFAULT NULL COMMENT '',
  `estado` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idproducto`)  COMMENT '',
  UNIQUE INDEX `idproducto_UNIQUE` (`idproducto` ASC)  COMMENT '',
  INDEX `fk_producto_categoria1_idx` (`idcategoria` ASC)  COMMENT '',
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `secutel-erp`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`detalle_cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`detalle_cotizacion` (
  `id_detalle_cotizacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idcotizacion` INT(11) NOT NULL COMMENT '',
  `idproducto` INT(11) NOT NULL COMMENT '',
  `cantidad` INT(11) NOT NULL COMMENT 'cantidad del producto o servicio a cotizar ',
  `valor` DOUBLE NOT NULL COMMENT 'valor de venta cotizado (sin impuesto)',
  PRIMARY KEY (`id_detalle_cotizacion`)  COMMENT '',
  UNIQUE INDEX `id_detalle_cotizacion_UNIQUE` (`id_detalle_cotizacion` ASC)  COMMENT '',
  INDEX `fk_detalle_cotizacion_cotizacion1_idx` (`idcotizacion` ASC)  COMMENT '',
  INDEX `fk_detalle_cotizacion_producto1_idx` (`idproducto` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_cotizacion_cotizacion1`
    FOREIGN KEY (`idcotizacion`)
    REFERENCES `secutel-erp`.`cotizacion` (`idCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_cotizacion_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `secutel-erp`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`sucursal` (
  `idsucursal` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idsucursal`)  COMMENT '',
  UNIQUE INDEX `idsucursal_UNIQUE` (`idsucursal` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`factura` (
  `idFactura` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `numero_factura` INT(11) NOT NULL COMMENT '',
  `idlocal` INT(11) NOT NULL COMMENT '',
  `idcliente` INT(11) NOT NULL COMMENT '',
  `idvendedor` INT(11) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `estado` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad_total_productos` INT(11) NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una factura, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  `sub_total` DOUBLE NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una factura, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  `iva` DOUBLE NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una factura, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  `total_pagar` DOUBLE NULL DEFAULT NULL COMMENT 'ese dato puede ser null, ya que al ingresar una factura, estos valores se calculan a travÔö£┬┐s de un mÔö£┬┐todo',
  `metodo_pago` VARCHAR(45) NULL DEFAULT NULL COMMENT 'el metodo de pago puede ser: credito, cheque o al contado.',
  PRIMARY KEY (`idFactura`)  COMMENT '',
  UNIQUE INDEX `idFactura_UNIQUE` (`idFactura` ASC)  COMMENT '',
  UNIQUE INDEX `numero_factura_UNIQUE` (`numero_factura` ASC)  COMMENT '',
  INDEX `fk_factura_empleado_idx` (`idvendedor` ASC)  COMMENT '',
  INDEX `fk_factura_cliente1_idx` (`idcliente` ASC)  COMMENT '',
  INDEX `fk_factura_sucursal1_idx` (`idlocal` ASC)  COMMENT '',
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `secutel-erp`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_empleado`
    FOREIGN KEY (`idvendedor`)
    REFERENCES `secutel-erp`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_sucursal1`
    FOREIGN KEY (`idlocal`)
    REFERENCES `secutel-erp`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`detalle_factura` (
  `iddetalle_factura` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idfactura` INT(11) NOT NULL COMMENT '',
  `idproducto` INT(11) NOT NULL COMMENT '',
  `cantidad` INT(11) NOT NULL COMMENT '',
  `valor` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`iddetalle_factura`)  COMMENT '',
  UNIQUE INDEX `iddetalle_factura_UNIQUE` (`iddetalle_factura` ASC)  COMMENT '',
  INDEX `fk_detalle_factura_factura1_idx` (`idfactura` ASC)  COMMENT '',
  INDEX `fk_detalle_factura_producto1_idx` (`idproducto` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_factura_factura1`
    FOREIGN KEY (`idfactura`)
    REFERENCES `secutel-erp`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_factura_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `secutel-erp`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`orden_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`orden_compra` (
  `idorden_compra` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idcontacto_proveedor` INT(11) NOT NULL COMMENT '',
  `idempleado` INT(11) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `estado` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad_total_productos` INT(11) NULL DEFAULT NULL COMMENT 'estos valores se calculan a traves de un metodo con los detalles de la orden de compra',
  `sub_total` DOUBLE NULL DEFAULT NULL COMMENT 'estos valores se calculan a traves de un metodo con los detalles de la orden de compra',
  `iva` DOUBLE NULL DEFAULT NULL COMMENT 'estos valores se calculan a traves de un metodo con los detalles de la orden de compra',
  `total_pagar` DOUBLE NULL DEFAULT NULL COMMENT 'estos valores se calculan a traves de un metodo con los detalles de la orden de compra',
  `estado_registro` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idorden_compra`)  COMMENT '',
  UNIQUE INDEX `idorden_compra_UNIQUE` (`idorden_compra` ASC)  COMMENT '',
  INDEX `fk_orden_compra_empleado1_idx` (`idempleado` ASC)  COMMENT '',
  INDEX `fk_orden_compra_contacto_proveedor1_idx` (`idcontacto_proveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_orden_compra_contacto_proveedor1`
    FOREIGN KEY (`idcontacto_proveedor`)
    REFERENCES `secutel-erp`.`contacto_proveedor` (`idcontacto_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_compra_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `secutel-erp`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`detalle_ordendecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`detalle_ordendecompra` (
  `iddetalle_ordenDeCompra` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idorden_compra` INT(11) NOT NULL COMMENT '',
  `idproducto` INT(11) NOT NULL COMMENT '',
  `cantidad` INT(11) NOT NULL COMMENT '',
  `valor_unitario` DOUBLE NOT NULL COMMENT '',
  `valor_total` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`iddetalle_ordenDeCompra`)  COMMENT '',
  UNIQUE INDEX `iddetalle_ordenDeCompra_UNIQUE` (`iddetalle_ordenDeCompra` ASC)  COMMENT '',
  INDEX `fk_detalle_ordendecompra_orden_compra1_idx` (`idorden_compra` ASC)  COMMENT '',
  INDEX `fk_detalle_ordendecompra_producto1_idx` (`idproducto` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_ordendecompra_orden_compra1`
    FOREIGN KEY (`idorden_compra`)
    REFERENCES `secutel-erp`.`orden_compra` (`idorden_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ordendecompra_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `secutel-erp`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`detalle_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`detalle_producto` (
  `iddetalle_producto` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idproducto` INT(11) NOT NULL COMMENT '',
  `numero_serie` VARCHAR(45) NOT NULL COMMENT '',
  `color` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`iddetalle_producto`)  COMMENT '',
  UNIQUE INDEX `iddetalle_producto_UNIQUE` (`iddetalle_producto` ASC)  COMMENT '',
  UNIQUE INDEX `numero_serie_UNIQUE` (`numero_serie` ASC)  COMMENT '',
  INDEX `fk_detalle_producto_producto1_idx` (`idproducto` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_producto_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `secutel-erp`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`kardex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`kardex` (
  `idkardex` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idproducto` INT(11) NOT NULL COMMENT '',
  `fecha_registro` DATE NOT NULL COMMENT '',
  `detalle` VARCHAR(45) NOT NULL COMMENT '',
  `valor_compra` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`idkardex`)  COMMENT '',
  UNIQUE INDEX `idkardex_UNIQUE` (`idkardex` ASC)  COMMENT '',
  INDEX `fk_kardex_producto1_idx` (`idproducto` ASC)  COMMENT '',
  CONSTRAINT `fk_kardex_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `secutel-erp`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `secutel-erp`.`tabla_telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secutel-erp`.`tabla_telefono` (
  `idtabla_telefono` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idcontacto` INT(11) NOT NULL COMMENT '',
  `numero` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idtabla_telefono`)  COMMENT '',
  UNIQUE INDEX `idtabla_telefono_UNIQUE` (`idtabla_telefono` ASC)  COMMENT '',
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC)  COMMENT '',
  INDEX `fk_tabla_telefono_contacto_proveedor1_idx` (`idcontacto` ASC)  COMMENT '',
  CONSTRAINT `fk_tabla_telefono_contacto_proveedor1`
    FOREIGN KEY (`idcontacto`)
    REFERENCES `secutel-erp`.`contacto_proveedor` (`idcontacto_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `secutel-erp` ;

-- -----------------------------------------------------
-- procedure consulta_info_empleado
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consulta_info_empleado`(in id varchar(45), out nom varchar(45), out tel varchar(45), 
out dir varchar(45), out fech date, out tip varchar(45), out est varchar(1) )
BEGIN
	select nombre, telefono, direccion, fecha_nacimiento, tipo, estado into nom, tel, dir, fech, tip, est 
    from empleado where cedula = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure consultar_detalles_cotizaciones
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consultar_detalles_cotizaciones`(in id int)
BEGIN
	select * from detalle_cotizacion where idcotizacion = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure consultar_detalles_factura
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consultar_detalles_factura`(in id int)
BEGIN
	select * from detalle_factura where idfactura = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure consultar_info_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consultar_info_cliente`(in id varchar(45), out nom varchar(45), 
out tel varchar(45), out corr varchar (45), out dir varchar(45), out tip varchar (45), 
out est varchar(1))
BEGIN
	select nombre, telefono, correo, direccion, tipo, estado into nom, tel, corr, dir, tip,
    est from cliente where cedula = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure consultar_todos_clientes
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consultar_todos_clientes`()
BEGIN
	select * from cliente;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure consultar_todos_empleados
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consultar_todos_empleados`()
BEGIN
	select * from empleado;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure consultar_todos_locales
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consultar_todos_locales`()
BEGIN
	select * from sucursal;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresar_detalle_cotizacion
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresar_detalle_cotizacion`(in idcot int, in idprod int, in cantidad int, in valor double)
BEGIN
	insert into detalle_cotizacion (idcotizacion, idproducto, cantidad, valor)
    value (idcot, idprod, cantidad, valor);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresar_detalle_factura
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresar_detalle_factura`(in idfactura int, in idproducto int, in cantidad int, in valor double)
BEGIN
	insert into detalle_factura (idfactura, idproducto, cantidad, valor)
    values (idfactura, idproudcto, cantidad, valor);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresar_usuario
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresar_usuario`(in empleado int, in user varchar(45), in clave varchar(45), in estado varchar(1))
BEGIN
	insert into credenciales (idempleado, usuario, clave, estado)
    values (empleado, user, clave, estado);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresarcliente
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresarcliente`(in nombre varchar(45), in cedula varchar(45), in telefono varchar(45), in correo varchar(45), in direccion varchar(45), in tipo varchar(45), in estado varchar(1))
BEGIN
insert into cliente (nombre, cedula, telefono, correo, direccion, tipo, estado)
values (nombre, cedula, telefono, correo, direccion, tipo, estado);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresarcotizacion
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresarcotizacion`(in cliente int (11), in vendedor int (11), in fecha date, in vigencia varchar(45), in estado varchar(45), in cantidad int(11), in subtotal double, in iva double, in total double)
BEGIN
insert into cotizacion (idcliente, idvendedor, fecha, vigencia, estado, cantidad_total, sub_total, impuestos, total_pagar)
values (cliente, vendedor, fecha, fecha, vigencia, estado, cantidad, subtotal, imp, total);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresarempleado
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresarempleado`(in nombre varchar(45), in cedula varchar(45), in telefono varchar(45), in direccion varchar(45), in fecha varchar(45), 
in tipo varchar(45), in estado varchar (1))
BEGIN
	insert into empleado (nombre, cedula, telefono, direccion, fecha_nacimiento, tipo, estado)
    values (nombre, cedula, telefono, direccion, fecha, tipo, estado);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresarfactura
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresarfactura`(in sucursal int(11), in numf int, in cliente int(11), in vendedor int(11), in fecha date, in estado varchar(45), in cantidad int(11), in subtotal double, in iva double, in total double, in pago varchar(45))
BEGIN
insert into factura (idlocal, numero_factura, idcliente, idvendedor, fecha, estado, cantidad_total_productos, sub_total, iva, total_pagar, metodo_pago)
values (sucursal, numf, cliente, vendedor, fecha, estado, cantidad, subtotal, imp, total, pago);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ingresarsucursal
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ingresarsucursal`(in nombre varchar(45), in direccion varchar(45), in estado varchar(1))
BEGIN
	insert into sucursal (nombre, direccion, estado)
    values (nombre, direccion, estado);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_detalle_cotizacion
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `modificar_detalle_cotizacion`(in id int, in idcot int, in idprod int, in cant int, in val double)
BEGIN
	update detalle_cotizacion
    set
		idcotizacion = idcot,
        idproducto = idprod,
        cant = cantidad,
        valor = valor
	where iddetalle_cotizacion = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_detalle_factura
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `modificar_detalle_factura`(in id int, in idfact int, in idprod int, in cant int, in val double)
BEGIN
	update detalle_factura
    set
		idfactura = idfact,
        idproducto = idprod,
        cant = cantidad,
        valor = valor
	where iddetalle_factura = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificarcliente
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `modificarcliente`(in id int(11), in nombre varchar(45), in cedula varchar(45), in telefono varchar(45), in correo varchar(45), in direccion varchar(45), in tipo varchar(45), in estado varchar(1))
BEGIN
update cliente
set
	nombre = nombre,
    cedula = cedula,
    telefono = telefono,
    correo = correo,
    direccion = direccion,
    tipo = tipo,
    estado = estado
where idcliente = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificarcotizacion
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `modificarcotizacion`(in id int (11), in cliente int (11), in vendedor int (11), in fecha date, in vigencia varchar(45), in estado varchar(45), in cantidad int(11), in subtotal double, in imp double, in total double)
BEGIN
update cotizacion
set
	idcliente = cliente,
    idvendedor = vendedor,
    fecha = fecha,
    vigencia = vigencia,
    estado = estado,
    cantidad_total = cantidad,
    sub_total = subtotal,
    impuestos = imp,
    total_pagar = total
where idCotizacion = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificarempleado
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `modificarempleado`(in id int (11), in nombre varchar(45), in cedula varchar(45), in telefono varchar(45), 
in direccion varchar(45), in fecha varchar(45), in tipo varchar(45), in estado varchar(1))
BEGIN
	update empleado
    set
		nombre = nombre,
        cedula = cedula,
        telefono = telefono,
        direccion = direccion,
        fecha_nacimiento = fecha,
        tipo = tipo,
        estado = estado
    where idempleado = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificarfactura
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `modificarfactura`(in id int(11), in numf int, in sucursal int(11), in cliente int(11), in vendedor int(11), in fecha date, in estado varchar(45), in cantidad int(11), in subtotal double, in imp double, in total double, in pago varchar(45))
BEGIN
	update factura
    set
		idlocal = sucursal,
        numero_factura = numf,
        idcliente = cliente,
        idvendedor = vendedor,
        fecha = fecha,
        estado = estado,
        cantidad_total_producto = cantidad,
        sub_total = subtotal,
        impuestos = imp,
        total_pagar = total,
        metodo_pago = pago
    where idFactura = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificarsucursal
-- -----------------------------------------------------

DELIMITER $$
USE `secutel-erp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `modificarsucursal`(in id int(11), in nombre varchar (45), in direccion varchar(45), in estado varchar (1))
BEGIN
	update sucursal
    set
		nombre = nombre,
        direccion = direccion,
        estado = estado
    where idsucursal = id;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
